### ISSUE TITLE
Error on viewing a commit

### ISSUE THREAD

**Issue by Migaloux** [tleish/redmine_revision_branches#11]
Hi,
I have an error when i try to view the detail of a commit.
See above the trace form the log of redmine (production.log)
Could you check the error ?

...Started GET "/redmine/projects/erp_auxilog/repository/revisions/619060ed94334714174a066fd29108622e0a905c" for ::1 at 2016-03-18 17:16:13 +0100
Processing by RepositoriesController#revision as HTML
  Parameters: {"id"=>"erp_auxilog", "rev"=>"619060ed94334714174a066fd29108622e0a905c"}
  Current user: s.gremling (id=10)
  Rendered repositories/_related_issues.html.erb (6.9ms)
  Rendered repositories/revision.html.erb (37.2ms)
  Rendered plugins/redmine_revision_branches/app/views/repositories/revision.html.erb within layouts/base (128.3ms)
Completed 500 Internal Server Error in 143ms (ActiveRecord: 6.3ms)

ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT):
    10:      end
    11:
    12:     html = linkify_id(html)
    13:     html = insert_branches_detail(html)
    14:   end
    15: %>
    16:
  app/controllers/repositories_controller.rb:223:in `revision'
  lib/redmine/sudo_mode.rb:63:in`sudo_mode'

**Comment by tleish** [comment]
Can you include the following:
- Redmine Version
- Ruby Version
- Rails Version
- Mysql2 Gem Version

**Comment by Migaloux** [comment]
Ok i can give this :
Redmine 3.2 (lastest)
ruby -v => ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
rails -v => Rails 4.2.5e
gem -v Msql => 2.2.2

**Comment by tleish** [comment]
Sorry, I need a little more information.  Please navigate to Administration > Information ([your redmine url]/admin/info) and post to here what is displayed on that screen.

**Comment by Migaloux** [comment]
like this :
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Git                            2.1.4
  Filesystem  
Redmine plugins:
  clipboard_image_paste          1.10
  redmine_custom_workflows       0.1.6
  redmine_image_clipboard_paste  1.0.0
  redmine_revision_branches      0.3.1
  redmine_spent_time             3.1.2
  redmine_stats                  0.0.3

**Comment by tleish** [comment]
I'm still unable to get to the bottom of this as I can't reproduce it.  Some research suggests this is an issue with how mysql db was encoded

This may be an issue with Rails 4.2.5 (see https://github.com/rails/rails/issues/23978).

It's not clear if it's coming from the html being passed to `linkify_id(html)` or somewhere else.  Are you able to debug a bit more a determine what the html looks like before and after these methods?

**Comment by Migaloux** [comment]
ok, thanks, i will try to upgrate Rails.

**Comment by tleish** [comment]
Any updates on this, or should I close the issue?

**Comment by Migaloux** [comment]
yes you can.
