### ISSUE TITLE
dependencies have fixed version, conflicting with existing install/plugins

### ISSUE THREAD

**Issue by simeonfelis** [tleish/redmine_revision_branches#13]
Running

```
rake redmine:plugins NAME=redmine_revision_branches RAILS_ENV=production
```

Results in 

```
Could not find coffee-script-source-1.3.3 in any of the sources
```

Installed with

```
gem install coffee-script-source --version 1.3.3
```

Because not specifying a version would result in a different version to be installed. Continued

```
Could not find execjs-2.2.1 in any of the sources
```

Installed with

```
gem install -V execjs --version 2.2.1
```

Because not specifying a version would result in a different version to be installed.  Continued:

```
Could not find coffee-script-2.2.0 in any of the sources
```

Aha! I have already this plugin in a newer version:

```
gem list | grep coffee-script
coffee-script (2.4.1)
coffee-script-source (1.10.0, 1.3.3)
```

Could you please make your dependencies more generic, eg. coffee-script >= 2.2.0 <= 3.0.0?

Thanks!

**Comment by tleish** [comment]
This plugin does not reference or have any dependencies on coffee-script or execjs.  You may want to check your other plugins.
