### ISSUE TITLE
"Associated Revisions" performance issue mitigation suggestion

### ISSUE THREAD

**Issue by thomas-riccardi** [tleish/redmine_revision_branches#14]
We have a workflow where we need the branches information added by this great plugin under "Associated Revisions", but the performance issue is too big:
~10 commits on an issue result in +4 second delay loading the page.
We cannot enable this feature as it is now.

The first idea to fix this is to use a cache.

But correctly caching the results is hard, because any operation on the git repository could invalidate the cached data: a new branch, a merge, a branche deletion etc.. would change the revision -> branch association for a lot of commits.

A cache with a simple Time To Live is not great either: 
- either the TTL is long and it will make the feature useless because the data would be too often and for too long out-of-date.
- or the TTL is too short and would mostly never be hit.

I looked into the gitlab source code to check how they implemented this feature, and they also call `git branch --contains`, and I haven't found caching for this data. However, they only seem to display this info in contexts where only one commit is analyzed (such as the commit details page), so they don't have the present issue of computing this for many commits for one page.

Thus, I suggest another approach: 
In our use-case the information is really useful, but not for everyone, and not all the time. So we could have the feature disabled by default, but the user should be able to enable it on demand (with no persistence of the demand), by a click of a button (or link).
If the user really wants it, he will accept the slowness.

Technically I can think of two solutions: either load the info with ajax, or have a (query string?) parameter for the issue page to compute.
We could still add a cache with a short TTL, it could help (and maybe give a way to the user to refresh the cache on demand for the current issue too).

**Comment by tleish** [comment]
What is the specific workflow requires you to view branches under "Associated Revisions" instead of under each revision?

**Comment by thomas-riccardi** [comment]
Given an issue with 15 associated revisions on master, we want to quickly see which ones have been cherry-picked on which branch, etc..
Opening 15 tabs to have the information is not only tedious but also not useful: the data is then spread on 16 tabs, it's not an aggregated view.

**Comment by tleish** [comment]
By aggregated, are you suggesting there would be 1 list... or a list of branches underneath each commit?  This could quickly get pretty messy.

**Comment by tleish** [comment]
Closing as I no longer use Redmine and cannot effectively update and maintain this repo.
