### ISSUE TITLE
Option to also display `git describe --tags --always`

### ISSUE THREAD

**Issue by YuukiHogo** [tleish/redmine_revision_branches#16]
Is it possible to add option to additionally show output of `git describe --tags --always` in associated commits and commit view? It is because of branch name is not descriptive enough to know which version contains commit;

**Comment by tleish** [comment]
Is this a common problem?  It's not that difficult to determine which branch contains which hash.

**Comment by YuukiHogo** [comment]
It is common issue to let know someone where in commit history specified commit is - before or after specific milestone. To obtain such information someone must clone repo.

**Comment by tleish** [comment]
Closing as I no longer use Redmine and cannot effectively update and maintain this repo.
