### ISSUE TITLE
Redmine 3.4.1: not working

### ISSUE THREAD

**Issue by akibukis** [tleish/redmine_revision_branches#18]
When you check both checkboxes in plugin settings, mysql table for a plugin gets updated with plugin settings. After refreshing plugin settings page, both checkboxes are unchecked (mysql table data stays valid):
```
---
display_under_single_revision: 'true'
display_under_associated_revisions: 'true'
```

Plugin is supposed to display Branch Lists, but it does not (same output as without the plugin). 
Asociated revisions in issues also do not contain any branches information.

I'm using Gitolite3 which is setup correctly along with redmine_git_hosting plugin v1.2.3 (config test passes 100%).
There are no errors in any of the logfiles....... ... HELP!!

Details about the installation:
![image](https://user-images.githubusercontent.com/1809502/28412738-c950f344-6d4d-11e7-8469-8ac693e66af3.png)
![image](https://user-images.githubusercontent.com/1809502/28412771-dbaeeb4a-6d4d-11e7-8876-4ebd56f213d1.png)
![image](https://user-images.githubusercontent.com/1809502/28412833-0b841bba-6d4e-11e7-8409-6b2ed7cfa6db.png)

**Comment by akibukis** [comment]
Anybody?? :(

**Comment by tleish** [comment]
Get the latest 0.3.2 and this should be fixed
