### ISSUE TITLE
Please add SVN support

### ISSUE THREAD

**Issue by optio** [tleish/redmine_revision_branches#2]
Hi,

Looks super usefull, though we're using SVN.

Is it possible to add SVN support ?

Thank you

**Comment by abatista75** [comment]
+1

The support to SVN would be very great, and that plugin will turn as a must-have.

**Comment by tleish** [comment]
This is built into git.  In the command line, you can simply run:

```
git branch --contains <commit>
```

This redmine plugin uses this built-in method.  If there is an equivalent in the svn command line, then this is a possibility.

### Workaround

A workaround might be to use git-svn on your redmine server.  Even if you don't use it in your standard development, it's read-only for Redmine.  

https://www.atlassian.com/git/tutorials/migrating-overview

This would allow you to use this plugin.
