### ISSUE TITLE
Revision not found for Git-flow feature branches

### ISSUE THREAD

**Issue by mickey9801** [tleish/redmine_revision_branches#6]
The "Branch" link will point to a wrong place if the repository follow gitflow workflow. For example: for a feature branch "feature_1", the path to the branch should be "feature/feature _1", but the link pointed to "feature_1"

**Comment by tleish** [comment]
I don't completely understand, can you provide more detail and more examples?

**Comment by mickey9801** [comment]
Sorry by English too bad to describe the situation. I use SourceTree to apply gitflow to my repository "wyof" and start a feature branch(e.g. import_member_excel). The path of the branch is "feature/import_member_excel" in both SourceTree and Redmine Repository page. But in Revision page, it shows as "import_member_excel" only and the URL to the branch's page is http://my.redmine/projects/wyof/repository/wyof/revisions/import_member_excel/show

It works fine for develop branch (a single level path).

---

Here are some screenshots:
<img width="573" alt="screen shot 2015-08-22 at 18 02 12" src="https://cloud.githubusercontent.com/assets/259019/9425052/13805066-4935-11e5-9f2d-aa7dd72a8b3b.png">
Path shown in Redmine repository page
<img width="427" alt="screen shot 2015-08-22 at 18 02 31" src="https://cloud.githubusercontent.com/assets/259019/9425053/13810a60-4935-11e5-8e80-f0fdae2afc96.png">
Path shown in Revision page (point to http://my.redmine/projects/wyof/repository/wyof/revisions/import_member_excel/show)
<img width="136" alt="screen shot 2015-08-23 at 01 01 45" src="https://cloud.githubusercontent.com/assets/259019/9425059/272de498-4935-11e5-8f61-d9172c4f0f2b.png">
Path shown in SourceTree
<img width="721" alt="screen shot 2015-08-23 at 01 03 46" src="https://cloud.githubusercontent.com/assets/259019/9425060/27334b90-4935-11e5-9c09-9bcd5d97a90a.png">
When I click the branch link in Revision page , I got 404 not found. It works fine for develop branch

**Comment by tleish** [comment]
For this branch, what is the correct URL in Redmine.  In other words, in Redmine if you navigate to _Repository_ within Redmine and select Branch: import_member_excel, what URL do you see?

**Comment by mickey9801** [comment]
http://my.redmine/projects/wyof/repository?utf8=%E2%9C%93&rev=feature%2Fimport_member_excel

I don't think it is the only URL I can show this branch. For example in Repository tab when I select "develop" branch, the URL is http://my.redmine/projects/wyof/repository?utf8=%E2%9C%93&rev=develop. But I can still use the URL in Revision page http://my.redmine/projects/wyof/repository/wyof/revisions/develop/show to reach the same page.

I have tried to amend the URL manually to http://my.redmine/projects/wyof/repository/wyof/revisions/feature%2Fimport_member_excel/show but it didn't work, even the template did not applied.

<img width="470" alt="screen shot 2015-08-23 at 15 12 52" src="https://cloud.githubusercontent.com/assets/259019/9427321/f569e5fe-49a9-11e5-9298-f2ae2acb65aa.png">

**Comment by tleish** [comment]
Get the latest and try again.

**Comment by mickey9801** [comment]
It works fine now. Thank you very much!
