### ISSUE TITLE
Branches are not shown (Redmine 3.1.0/plugin HEAD)

### ISSUE THREAD

**Issue by modprobe** [tleish/redmine_revision_branches#7]
From the logs, everything seems fine:

```
$ cat production.log | grep -in "branch" | tail
114888:  Parameters: {"id"=>"redmine_revision_branches"}
114890:  Rendered plugins/redmine_revision_branches/app/views/redmine_revision_branches/_settings.html.erb (0.6ms)
114899:Started POST "/redmine/settings/plugin/redmine_revision_branches" for XX.XX.XX.XX at 2015-11-09 11:28:40 +0100
114901:  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[REDACTED]", "settings"=>{"display_under_single_revision"=>"true", "display_under_associated_revisions"=>"true"}, "commit"=>"Apply", "id"=>"redmine_revision_branches"}
114903:Redirected to https://[redminehost]/redmine/settings/plugin/redmine_revision_branches
114905:Started GET "/redmine/settings/plugin/redmine_revision_branches" for XX.XX.XX.XX at 2015-11-09 11:28:40 +0100
114907:  Parameters: {"id"=>"redmine_revision_branches"}
114910:  Rendered plugins/redmine_revision_branches/app/views/redmine_revision_branches/_settings.html.erb (0.5ms)
115003:  Rendered plugins/redmine_revision_branches/app/views/issues/_changesets.html.erb (29.6ms)
115033:  Rendered plugins/redmine_revision_branches/app/views/repositories/revision.html.erb within layouts/base (135.7ms)
```

While the plugin code is relatively easy to comprehend, the integration into the redmine SCM adapter makes it very intransparent.

Judging from the `_changesets` view and as there are no exceptions, I would suspect this line: 

``` ruby
return [] unless has_branch_detail?
```

and therefore the method `has_branch_detail?` to return false. Maybe the git adapter patch is not loaded properly, but I have no idea why that would be the case.

I would appreciate help in tracking this bug down.

---

Screenshots:

![redmine_branch_1](https://cloud.githubusercontent.com/assets/4273389/11031639/3928b7de-86d6-11e5-9d83-54b15cc97695.png)
![redmine_branch_2](https://cloud.githubusercontent.com/assets/4273389/11031640/3928e42a-86d6-11e5-86b1-6abcf5117f10.png)

**Comment by tleish** [comment]
Just committed branch `issue-7-branches-not-shown` with commit to output log error when there's a problem with git (see: 9747ad971dc5e5de539839ce794e3b33c9d6e9ba).  Try this branch and see if this helps you track down the issue.

Also, what settings did you configure in Plugin > Revision Branches > Configure?

**Comment by modprobe** [comment]
Unfortunately there is no change. Nothing is written to the logs, which reinforces my belief that the git adapter patch is not loaded. 

Maybe I'm on the wrong path, but I think it would not be noticeable if it weren't loaded, because `has_branch_detail?` uses `respond_to?` to check if `branch_contains` exists, and the only other place it would be called is in `branch_groups`, which itself is never called because `links_to_branches` returns beforehand.

I have enabled both the single and associated revisions options.

**Comment by tleish** [comment]
Please provide your Plugin Configuration settings.

Go to Plugin > Revision Branches > Configure to enable/disable parts of the application.
![Screenshot](https://raw.githubusercontent.com/tleish/redmine_revision_branches/master/screenshot_configure.png)

**Comment by modprobe** [comment]
I have tried all possible combinations of the two options. It makes no difference.

**EDIT:** I have added some debug messages and it is indeed the case that 

``` ruby
@repository.scm.respond_to? :branch_contains
```

returns `false` and

``` ruby
branch_groups.map { |name, branches| branches_link(name, branches) }
```

is therefore never executed.

**Comment by tleish** [comment]
What does the following output?

``` ruby
@repository.scm.class #=> ?
```

**Comment by modprobe** [comment]
Oh, good catch. The class of the SCM adapter is indeed `Redmine::Scm::Adapters::XitoliteAdapter` (which comes from the `redmine_git_hosting` plugin), and not the patched `Redmine::Scm::Adapters::GitAdapter`. Now that I know that it should be easy to fix. 

Thanks for your help! :)
