### ISSUE TITLE
Show branch in Actvity log

### ISSUE THREAD

**Issue by xJom** [tleish/redmine_revision_branches#8]
Is it possible to also add the branch to the activity log?

So the output would be:

Revision SHA (repo@branch): Description

instead of

Revision SHA (repo): Description

**Comment by tleish** [comment]
Which activity log are you referring to?

**Comment by xJom** [comment]
This: http://www.redmine.org/projects/redmine/wiki/RedmineProjectActivity

**Comment by tleish** [comment]
This is possible, but the performance on it would be very poor.  Git doesn't provide a way to get a batch list of commits/branches, it must be queried one commit at a time.  There are already performance implications when enabling this on Associated Revisions.  Doing so for the activity log would be much more.
